# Numpy Array Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[7]

7

In [5]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [6]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[0:5]=100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
slice_of_arr = arr[0:7]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
copy_of_arr = arr[:]

In [16]:
copy_of_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
copy_of_arr[:]=17

In [18]:
copy_of_arr

array([17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17])

In [19]:
arr

array([17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17])

Copy Array:

In [20]:
copy_arr = arr.copy()

In [21]:
copy_arr

array([17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17])

In [22]:
copy_arr[:]=33

In [23]:
copy_arr

array([33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33])

In [24]:
arr

array([17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17])

In [28]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing of 2D Array:

In [31]:
arr_2d = np.array([[5,10,15],[20,25,30],[40,45,50]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [40, 45, 50]])

### 2 ways of Indexing Array:

1. Double Bracket Format:

In [33]:
arr_2d[0][0]

5

In [34]:
arr_2d[1]

array([20, 25, 30])

In [38]:
arr_2d[1][2]

30

2. Single Bracket with Comma ',' format:

In [39]:
arr_2d[2,2]

50

### Slicing Matrix into sub-matrices:

In [40]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr_2d[1:,:2]

array([[20, 25],
       [40, 45]])

In [43]:
arr_2d[1:,1:]

array([[25, 30],
       [45, 50]])

In [44]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

## Conditional Selection

In [45]:
arr = np.arange(1, 11)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
bool_arr = arr>5

In [49]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [52]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [55]:
arr[arr<3]

array([1, 2])

Exercise:

In [56]:
arr_2d = np.arange(25).reshape(5,5)

In [57]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr_2d[2:4, 1:3]

array([[11, 12],
       [16, 17]])

In [59]:
arr_2d[2:5, 2:5]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

Great Job !!