# NumPy Array: Tutorial 1

In [97]:
print('Hello World.')

Hello World.


In [4]:
my_list = [1, 2, 4, 5, 6, 7,]

importing NumPy:

In [5]:
import numpy as np

Create Array:

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 4, 5, 6, 7])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_mat
        )

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Creating Array using: Built-in Generation Method:

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

Creating Null Matrix:

In [24]:
np.zeros((3,3, 3), dtype=float)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [26]:
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

Creation of Evenly Spaced numbers of Array:

In [43]:
np.linspace(0, 10, 5, endpoint=False, retstep=True, dtype=None, axis=0)

(array([0., 2., 4., 6., 8.]), 2.0)

In [45]:
np.linspace(0, 10, 4, endpoint=False, retstep=True, dtype=int, axis=0)

(array([0, 2, 5, 7]), 2.5)

In [46]:
np.linspace(0, 10, 4, endpoint=False, retstep=True, dtype=float, axis=0)

(array([0. , 2.5, 5. , 7.5]), 2.5)

Creating Identity Matrix:

In [47]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [48]:
np.eye(1)

array([[1.]])

In [65]:
np.eye(3, 2, k=0,dtype=float, order='F')

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Creating Array of Random Numbers:

In [68]:
np.random.rand(5, 5)

array([[0.49538621, 0.47396543, 0.05152941, 0.07001227, 0.88922783],
       [0.19649057, 0.3764135 , 0.96282166, 0.2313831 , 0.10605313],
       [0.07077181, 0.6436068 , 0.83526245, 0.21061046, 0.39051426],
       [0.7963428 , 0.55632018, 0.41798743, 0.23889606, 0.79441357],
       [0.97437835, 0.27729776, 0.00146417, 0.49851508, 0.53033711]])

In [69]:
np.random.rand(5)

array([0.28411993, 0.4761815 , 0.1453366 , 0.07054748, 0.26968382])

Returns the Array of sample/samples from the "Standard Normal Distrbution" or "Gaussioan Distribution":

In [70]:
np.random.randn(5)

array([-0.73764074,  1.54783307,  0.0886309 ,  0.54377726, -0.26871935])

In [71]:
np.random.randn(5, 5)

array([[-0.3575219 ,  0.94131352,  0.7530239 , -0.08035488, -0.66116705],
       [-1.30087428,  0.11442502, -0.6116236 , -0.56755539,  0.43213462],
       [-0.35054276, -1.63722586,  1.5409217 ,  0.8001833 ,  1.42843657],
       [-2.18875104,  1.02680922, -0.91747713, -0.05234565,  0.8781208 ],
       [ 0.3608036 , -1.26585098,  0.90062168,  1.46374774,  0.33779198]])

Creating Array of Random Integers:

In [73]:
np.random.randint(50)

45

In [74]:
np.random.randint(10, 100)

38

In [75]:
np.random.randint(1, 50, 10)

array([25, 18,  4, 33, 13, 47, 44, 31, 26, 29])

Useful Attributes and Methods in Array:

In [76]:
arr = np.arange(0, 25)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
ranarr = np.random.randint(0,50,10)

In [79]:
ranarr

array([ 7, 16, 34, 41, 42, 15,  9,  8,  0, 33])

In [80]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
ranarr.max()

42

In [86]:
ranarr.min()

0

In [87]:
ranarr.argmax()

4

In [88]:
ranarr.argmin()

8

In [89]:
ranarr.shape

(10,)

In [90]:
arr.shape

(25,)

In [91]:
arr = arr.reshape(5,5)

In [92]:
arr.shape

(5, 5)

In [93]:
arr.dtype

dtype('int64')

In [94]:
ranarr.dtype

dtype('int64')

Import random package from Numpy:

In [95]:
from numpy.random import randint

In [96]:
randint(1, 20, 5)

array([ 3,  2, 11, 10,  6])

Great Work !!